image: gradle:7.3.3-jdk17-alpine

# Definimos las etapas del trabajo de CI
stages:
  - build
  - test
  - sonar

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  SPRING_PROFILES_ACTIVE: test

build:
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew build
    - gradle build jacocoTestReport

test:
  stage: test
  script:
    - chmod +x ./gradlew
    - ./gradlew test

sonar:
  stage: sonar
  script:
    - chmod +x ./gradlew
    - ./gradlew sonar -D sonar.host.url=$SONAR_HOST_URL -D sonar.login=$SONAR_LOGIN -D sonar.password=$SONAR_PASSWORD
  only:
    - main