FROM ubuntu:latest as build
RUN apt-get update
RUN apt-get install open jdk-17-jdk -y
COPY . .
RUN ./gradlew bootJar --no-daemon

FROM open jdk:17-jdk-slim
EXPOSE 8080
COPY --from-build/build/libs/demo-1.jar app.jar
