name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Compile
        run: ./gradlew compileJava
      - name: Test
        run: ./gradlew test
      - name: Jar
        run: ./gradlew bootJar
      - name: analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube --info
      - name: Configurar credenciales de Git
        run: |
          git config --global user.name "Nombre de usuario"
          git config --global user.email "correo@example.com"
          git config --global credential.helper store
          git config --global credential.helper "store --file=.git-credentials"
          echo "https://${{ secrets.GITLAB_TOKEN }}@gitlab.com" > .git-credentials
      
      - name: Agregar URL remota de GitLab
        run: git remote add gitlab https://gitlab.com/traffic-agent/traffic-agent-backend-2023.git
    
      - name: Enviar cambios a GitLab
        run: git push gitlab main
