name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Compile
        run: ./gradlew compileJava
      - name: Test
        run: ./gradlew test
      - name: Jar
        run: ./gradlew bootJar
      - name: analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube --info
      - name: Push to GitLab
        run: |
          # Clonar el repositorio de GitLab
          git clone ${{ secrets.GITLAB_URL }} gitlab-repo
        
          # Copiar los archivos compilados/empaquetados a la carpeta clonada
          cp -R build/* gitlab-repo/
        
          # Navegar a la carpeta clonada
          cd gitlab-repo
                  
          # Configurar git para realizar el envío
          git config --global user.name "SantiagoCardenasFranco"
          git config --global user.email "santicarfranco8@gmail.com"
          git config --global credential.helper "store --file=.git-credentials"

          echo "https://${{ secrets.GITLAB_TOKEN }}@gitlab.com/SantiagoCardenasFranco/Traffic-Agent-Backend 2023.git" > remote_url
          git add .
          git commit -m "Actualizar archivos compilados/emepaquetados"
        
          git push origin main
